name: Pull Request

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: |
        ruby .github/osia_convert.rb
        gem install awesome_bot
        ruby .github/osia_get_links.rb
        awesome_bot check-unique.txt --allow-ssl -a 302,429 -w xbmc/xbmc
        gem install json_schema
        validate-schema .github/schema.json contents.json
        ruby .github/osia_validate_categories.rb
