name: Update Metadata

on: [workflow_dispatch, push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Run scripts
      run: |
        gem install octokit
        ruby .github/osia_update_github.rb
